[package]
name = "numera"
description = "numbers"
version = "0.0.3"
edition = "2021"
rust-version = "1.62"
authors = ["José Luis Cruz <joseluis@andamira.net>"]
repository = "https://github.com/andamira/numera"
documentation = "https://docs.rs/numera"
license = "MIT/Apache-2.0"
include = [
	"/src/**/*.rs",
	"/Cargo.toml",
	"/res/*",
	"/LICENSE-*.md",
	"/README.md",
]
categories = ["mathematics", "data-structures"]
keywords = ["math", "mathematics", "number", "numeral", "numeric"]
publish = false

[dependencies]

# optional external types
twofloat = { version = "0.5.0", optional = true, default-features = false }
half = { version = "2.0.0", optional = true, default-features = false  }
ibig = { version = "0.3.5", optional = true, default-features = false }

[dev-dependencies]
static_assertions = "1.1.0"

[features]
default = [ "std" ]
std = [ "half?/std", "ibig?/std" ]
all = [ "std", "twofloat", "half", "ibig" ]

[package.metadata.docs.rs]
rustdoc-args = [ "--html-in-header", "./res/header.html" ]

[badges]
maintenance = { status = "actively-developed" }
