[package]
name = "numera"
description = "numbers, arithmetic"
version = "0.0.2"
edition = "2021"
rust-version = "1.57"
authors = ["José Luis Cruz <joseluis@andamira.net>"]
repository = "https://github.com/andamira/numera"
documentation = "https://docs.rs/numera"
license = "MIT/Apache-2.0"
include = [
	"/src/**/*.rs",
	"/Cargo.toml",
	"/res/*",
	"/LICENSE-*.md",
	"/README.md",
]
categories = ["mathematics", "data-structures"]
keywords = ["math", "mathematics", "number", "numeral", "numeric"]
publish = false

[dependencies]
num-integer = "^0.1" # https://docs.rs/num-integer/
num-traits = "^0.2"  # https://docs.rs/num-traits/

float_eq = "^0.7"

[dev-dependencies]

[build-dependencies]

[package.metadata.docs.rs]
rustdoc-args = [ "--html-in-header", "./res/header.html" ]

[badges]
maintenance = { status = "actively-developed" }
