[package]
name = "numera"
description = "numbers"
version = "0.3.0"
edition = "2021"
rust-version = "1.67"
authors = ["José Luis Cruz <joseluis@andamira.net>"]
repository = "https://github.com/andamira/numera"
documentation = "https://docs.rs/numera"
license = "MIT OR Apache-2.0"
include = [
	"/src/**/*.rs",
	"/Cargo.toml",
	"/res/*.html",
	"/LICENSE-*.md",
	"/README.md",
]
categories = ["mathematics", "data-structures"]
keywords = ["math", "mathematics", "number", "numeral", "numeric"]
publish = true

[features]
default = ["std", "safe", "try_from"]

std = ["devela/std", "half?/std", "ibig?/std", "primal-sieve"]
safe = ["devela/safe"]
unsafe = []
nightly = [] # used only for docs

#* extras *#

# Enables all the `TryFrom` impls, (+3s compilation time in my system).
try_from = []

deps_all = ["twofloat", "half", "ibig"]


[dependencies]
devela = { version = "0.3.0", default-features = false }

#* optional *#

half = { version = "2.2.1", optional = true, default-features = false  }
ibig = { version = "0.3.6", optional = true, default-features = false }
primal-sieve = { version = "0.3.6", optional = true }
twofloat = { version = "0.6.1", optional = true, default-features = false }

[dev-dependencies]
static_assertions = "1.1.0"


[profile.dev]
opt-level = 3 # for faster prime testing


[package.metadata.docs.rs]
no-default-features = true
features = ["nightly", "std", "try_from", "deps_all"]
rustdoc-args = [ "--html-in-header", "./res/rustdoc-header.html" ]

[badges]
maintenance = { status = "experimental" }
