[package]
name = "numera"
description = "numbers"
version = "0.0.3"
edition = "2021"
rust-version = "1.62"
authors = ["José Luis Cruz <joseluis@andamira.net>"]
repository = "https://github.com/andamira/numera"
documentation = "https://docs.rs/numera"
license = "MIT/Apache-2.0"
include = [
	"/src/**/*.rs",
	"/Cargo.toml",
	"/res/*",
	"/LICENSE-*.md",
	"/README.md",
]
categories = ["mathematics", "data-structures"]
keywords = ["math", "mathematics", "number", "numeral", "numeric"]
publish = false

[dependencies]
num-integer = { version = "0.1.45", optional = true, default-features = false, features = ["i128"] }
num-traits = { version = "0.2.15", optional = true, default-features = false, features = ["i128"] }

twofloat = { version = "0.5.0", optional = true, default-features = false }
half = { version = "2.0.0", optional = true, default-features = false  }

[dev-dependencies]
static_assertions = "1.1.0"

[features]
default = ["std"]
std = [ "half?/std", "num-traits?/std", "num-integer?/std" ]
all = [ "std", "twofloat", "half", "num-traits", "num-integer" ]

[build-dependencies]

[package.metadata.docs.rs]
rustdoc-args = [ "--html-in-header", "./res/header.html" ]

[badges]
maintenance = { status = "actively-developed" }
