[package]
name = "numera"
description = "numbers, arithmetic"
version = "0.0.1"
edition = "2021"
rust-version = "1.57"
authors = ["José Luis Cruz <joseluis@andamira.net>"]
repository = "https://github.com/andamira/numera"
documentation = "https://docs.rs/numera"
license = "MIT/Apache-2.0"
include = [
	"src/**/*.rs",
	"Cargo.toml",
	"LICENSE*",
	"README.md",
]
categories = ["mathematics", "data-structures"]
keywords = ["math", "mathematics", "number", "numeral", "numeric"]
publish = false

[dependencies]
num-integer = "^0.1" # https://docs.rs/num-integer/
num-traits = "^0.2"  # https://docs.rs/num-traits/

float_eq = "^0.7"

# f16 & bf16
half = { version = "^1.8", features = ["num-traits"] }

# ± f8
# ufloat8 = "0.1.0"

# ± f128
# twofloat = "0.4.1" # WAITING for 0.5 with num-traits support
# twofloat =  { git = "https://github.com/ajtribick/twofloat/" }

[dev-dependencies]

[build-dependencies]

[package.metadata.docs.rs]
rustdoc-args = [ "--html-in-header", "./src/docs-header.html" ]

[badges]
# https://doc.rust-lang.org/cargo/reference/manifest.html#the-badges-section
maintenance = { status = "actively-developed" }
