[package]
name = "numera"
description = "numbers"
version = "0.3.0"
edition = "2021"
rust-version = "1.60" # sync with CI
authors = ["José Luis Cruz <joseluis@andamira.net>"]
repository = "https://github.com/andamira/numera"
documentation = "https://docs.rs/numera"
license = "MIT OR Apache-2.0"
include = [
	"/src/**/*.rs",
	"/Cargo.toml",
	"/res/*.html",
	"/LICENSE-*.md",
	"/README.md",
]
categories = ["mathematics", "data-structures"]
keywords = ["math", "mathematics", "number", "numeral", "numeric"]
publish = true

[features]
default = ["std", "safe"]
#
std = ["primal-sieve", "half?/std", "ibig?/std"]
#
safe = []
unsafe = []
#
nightly = [] # used only for docs

deps_all = ["twofloat", "half", "ibig"]

[dependencies]
az = "1.2.1"
paste = "1.0.12"

primal-sieve = { version = "0.3.6", optional = true }

# optional external numeric types
twofloat = { version = "0.6.1", optional = true, default-features = false }
half = { version = "2.2.1", optional = true, default-features = false  }
ibig = { version = "0.3.6", optional = true, default-features = false }

[dev-dependencies]
static_assertions = "1.1.0"


[profile.dev]
opt-level = 3


[package.metadata.docs.rs]
no-default-features = true
features = ["nightly", "std", "deps_all"]
rustdoc-args = [ "--html-in-header", "./res/rustdoc-header.html" ]

[badges]
maintenance = { status = "experimental" }
