[package]
name = "numera"
description = "numbers"
version = "0.1.0"
edition = "2021"
rust-version = "1.65"
authors = ["José Luis Cruz <joseluis@andamira.net>"]
repository = "https://github.com/andamira/numera"
documentation = "https://docs.rs/numera"
license = "MIT/Apache-2.0"
include = [
	"/src/**/*.rs",
	"/Cargo.toml",
	"/res/*.html",
	"/LICENSE-*.md",
	"/README.md",
]
categories = ["mathematics", "data-structures"]
keywords = ["math", "mathematics", "number", "numeral", "numeric"]
publish = false

[features]
default = ["std"]
#
std = ["half?/std", "ibig?/std"]
#
deps_all = ["twofloat", "half", "ibig"]
#
nightly = [] # used only for docs


[dependencies]
az = "1.2.1"
paste = "1.0.12"
primal-sieve = "0.3.6"

# optional external numeric types
twofloat = { version = "0.6.1", optional = true, default-features = false }
half = { version = "2.2.1", optional = true, default-features = false  }
ibig = { version = "0.3.6", optional = true, default-features = false }

[dev-dependencies]
static_assertions = "1.1.0"


[profile.dev]
opt-level = 3


[package.metadata.docs.rs]
features = ["nightly", "deps_all"]
rustdoc-args = [ "--html-in-header", "./res/rustdoc-header.html" ]

[badges]
maintenance = { status = "actively-developed" }
