[alias]

# CHECK
cl = "clippy" # std, safe
#
cla = "clippy --features=deps_all" # std, safe, all-dependencies
clu = "clippy --no-default-features --features=std" # std, unsafe
cln = "clippy --no-default-features --features=safe" # no-std, safe
clnu = "clippy --no-default-features" # no-std, unsafe

# CLEAN PACKAGE
cp = "clean --package"
crp = "clean --release --package"

# DOC
d = "doc --no-deps"
do = "doc --no-deps --open"
dd = "doc"
ddo = "doc --open"
#
da = "doc --no-deps --features=deps_all"
doa = "doc --no-deps --open --features=deps_all"
#
dn = "doc --no-deps --no-default-features"
don = "doc --no-deps --open --no-default-features"
# +nightly; document everything
nd = "doc --no-deps --features=nightly,deps_all"
ndo = "doc --no-deps --open --features=nightly,deps_all"
ndd = "doc --features=nightly,deps_all"
nddo = "doc --open --features=nightly,deps_all"


# BUILD
b = "build"
bb = "build --bin"
be = "build --example"
br = "build --release"
brb = "build --release --bin"
bre = "build --release --example"

# RUN
r = "run"
rb = "run --bin"
re = "run --example"
rr = "run --release"
rrb = "run --release --bin"
rre = "run --release --example"

# TEST
t = "test"
td = "test --doc"
t_ = "test -- --nocapture"
t_1 = "test -- --test-threads 1 --nocapture"
#
ta = "test --features=deps_all"
tda = "test --features=deps_all --doc"
ta_ = "test --features=deps_all -- --nocapture"
ta_1 = "test --features=deps_all -- --test-threads 1 --nocapture"
#
tn = "test --no-default-features"
tdn = "test --no-default-features --doc"
tn_ = "test --no-default-features -- --nocapture"
tn_1 = "test --no-default-features -- --test-threads 1 --nocapture"

# PUBLISH
p = "publish --dry-run"
pa = "publish --dry-run --allow-dirty"
pp = "publish"
ppa = "publish --allow-dirty"

# Cargo subcommands:
## cargo-expand
E = "expand"
Eb = "expand --bin"
Ee = "expand --example"
El = "expand --lib"

[build]
rustdocflags = [ "--html-in-header", "./res/rustdoc-header.html"]
