# TODO:simplify a bit

[alias]

# CHECK
c = "check" # std, safe
cr = "check --release" # std, safe
# fast compilation without costly features
cF = "check --no-default-features --features=std,safe" # std, safe
cnF = "check --no-default-features --features=safe" # no-std, safe
cuF = "check --no-default-features --features=std" # std, unsafe
cnuF = "check --no-default-features" # no-std, unsafe

# CLIPPY
cl = "clippy" # std, safe
clr = "clippy --release" # std, safe
#
cla = "clippy --features=deps_all" # std, safe, all deps
clu = "clippy --no-default-features --features=std" # std, unsafe
cln = "clippy --no-default-features --features=safe" # no-std, safe
clau = "clippy --no-default-features --features=std,deps_all" # std, unsafe, all deps
clnu = "clippy --no-default-features" # no-std, unsafe
#
clra = "clippy --release --features=deps_all" # std, safe, all deps
clru = "clippy --release --no-default-features --features=std" # std, unsafe
clrn = "clippy --release --no-default-features --features=safe" # no-std, safe
clrau = "clippy --release --no-default-features --features=std,deps_all" # std, unsafe, all deps
clrnu = "clippy --release --no-default-features" # no-std, unsafe
# fast compilation (no `try_from`)
clF = "clippy --no-default-features --features=std,safe" # std, safe
cluF = "clippy --no-default-features --features=std" # std, unsafe
clnF = "clippy --no-default-features --features=safe" # no-std, safe
clnuF = "clippy --no-default-features" # no-std, unsafe

# CLEAN PACKAGE
cp = "clean --package"
crp = "clean --release --package"

# DOC
d = "doc --no-deps"
do = "doc --no-deps --open"
dd = "doc"
ddo = "doc --open"
#
da = "doc --no-deps --features=deps_all"
doa = "doc --no-deps --open --features=deps_all"
#
dn = "doc --no-deps --no-default-features"
don = "doc --no-deps --open --no-default-features"
# +nightly; document everything, unsafe
nd = "doc --no-deps --no-default-features --features=nightly,std,try_from,deps_all"
ndo = "doc --no-deps --no-default-features --open --features=nightly,std,try_from,deps_all"
# fast
ndF = "doc --no-deps --no-default-features --features=nightly,std,deps_all"
ndoF = "doc --no-deps --no-default-features --open --features=nightly,std,deps_all"
# safe
nds = "doc --no-deps --features=nightly,deps_all"
ndso = "doc --no-deps --open --features=nightly,deps_all"

# BUILD
b = "build"
bb = "build --bin"
be = "build --example"
br = "build --release"
brb = "build --release --bin"
bre = "build --release --example"

# RUN
r = "run"
rb = "run --bin"
rr = "run --release"
rrb = "run --release --bin"
rre = "run --release --example"
# examples
re = "run --example"
rrue = "run --release --example --no-default-features --features=std,try_from" # unsafe
# examples, Fast compilation
reF = "run --no-default-features --features=std,safe --example"
rreF = "run --release --example --no-default-features --features=std,safe"

# TEST
# std, safe
t = "test"
td = "test --doc"
t_ = "test  -- --nocapture"
t_1 = "test -- --test-threads 1 --nocapture"
# std, safe, all dependencies
ta = "test --features=deps_all"
tda = "test --features=deps_all --doc"
ta_ = "test --features=deps_all -- --nocapture"
ta_1 = "test --features=deps_all -- --test-threads 1 --nocapture"
# std, unsafe
tu = "test --no-default-features --features=std"
tdu = "test --no-default-features --features=std --doc"
tu_ = "test --no-default-features --features=std -- --nocapture"
tu_1 = "test --no-default-features --features=std -- --test-threads 1 --nocapture"
# no-std, unsafe
tn = "test --no-default-features"
tdn = "test --no-default-features --doc"
tn_ = "test --no-default-features -- --nocapture"
tn_1 = "test --no-default-features -- --test-threads 1 --nocapture"
# Fast
tF = "test --no-default-features --features=std,safe"
tdF = "test --doc --no-default-features --features=std,safe"

# PUBLISH
p = "publish --dry-run"
pa = "publish --dry-run --allow-dirty"
pp = "publish"
ppa = "publish --allow-dirty"

# Cargo subcommands:
## cargo-expand
E = "expand"
Eb = "expand --bin"
Ee = "expand --example"
El = "expand --lib"

[build]
rustdocflags = [ "--html-in-header", "./res/rustdoc-header.html"]
