[alias]

# CHECK
cl = "clippy"
clq = "clippy --quiet"
#
cla = "clippy --features=all"
cln = "clippy --no-default-features"

# CLEAN PACKAGE
cp = "clean --package"
crp = "clean --release --package"

# DOC
d = "doc --no-deps"
do = "doc --no-deps --open"
dd = "doc"
ddo = "doc --open"
#
da = "doc --no-deps --features=all"
doa = "doc --no-deps --open --features=all"
#
dn = "doc --no-deps --no-default-features"
don = "doc --no-deps --open --no-default-features"

# BUILD
b = "build"
bb = "build --bin"
be = "build --example"
bq = "build --quiet"
br = "build --release"
bqb = "build --quiet --bin"
bqe = "build --quiet --example"
brb = "build --release --bin"
bre = "build --release --example"
brqb = "build --release --quiet --bin"
brqe = "build --release --quiet --example"

# RUN
r = "run"
rb = "run --bin"
re = "run --example"
rq = "run --quiet"
rr = "run --release"
rqb = "run --quiet --bin"
rqe = "run --quiet --example"
rrb = "run --release --bin"
rre = "run --release --example"
rrqb = "run --release --quiet --bin"
rrqe = "run --release --quiet --example"

# TEST
t = "test"
td = "test --doc"
t_ = "test -- --nocapture"
t_1 = "test -- --test-threads 1 --nocapture"
#
ta = "test --features=all"
tda = "test --features=all --doc"
ta_ = "test --features=all -- --nocapture"
ta_1 = "test --features=all -- --test-threads 1 --nocapture"
#
tn = "test --no-default-features"
tdn = "test --no-default-features --doc"
tn_ = "test --no-default-features -- --nocapture"
tn_1 = "test --no-default-features -- --test-threads 1 --nocapture"

# PUBLISH
p = "publish --dry-run"
pa = "publish --dry-run --allow-dirty"
pp = "publish"
ppa = "publish --allow-dirty"

# Cargo subcommands:
## cargo-expand
E = "expand"
Eb = "expand --bin"
Ee = "expand --example"
El = "expand --lib"

[build]
rustdocflags = [ "--html-in-header", "./res/rustdoc-header.html"]
